### ISSUE TITLE
ruby 2.7 for windows build

### ISSUE THREAD

**Issue by winezer0** [noraj/haiti#191]
Please Keep ruby27, Thank you very much.

I packaged haiti as windows exe 

https://github.com/winezer0/haiti.exe

But the packaging tool 'rubyc' only supports ruby27

**Comment by noraj** [comment]
Hi,

You have several options:

- [ ] Only create .exe for versions [until 2.1.0](https://github.com/noraj/haiti/blob/master/docs/CHANGELOG.md#210) (before 2.7 support removal)
- [ ] For now, ignore Ruby requirement
  - Indeed, Ruby 2.7 support [was removed](https://github.com/noraj/haiti/commit/8d614c9604cb7bcb6abc40aac95130bb44a5c3dd) for several reasons: because it's EOL, because [it made the CI fails](https://github.com/noraj/haiti/actions/runs/8630686708/job/23657488761).
  - But Ruby 2.7 should still work, for now, since I did not introduce breakings changes (for examples while linting with newer syntaxes).
  - For example, `gem install --force` ignores dependency checks. Another option is to create a patch to change the version required in the gemspec.
  - For now, forcing the use of Ruby 2.7 should have no impact, but I can't guarantee that in the future. For now, it should work, it's just that's no longer tested against ruby 2.7 and that I won't provide help for people using this version.
- [ ] Ruby 3.0-3.3 are available on Windows via [RubyInstaller](https://rubyinstaller.org/) so you could install haiti with `gem install haiti-hash` on windows too without making a `.exe.`.
- [ ] Use another executable packager other than the unmaintained [ruby-packer](https://github.com/pmq20/ruby-packer)
  - [ ] [tebako](https://github.com/tamatebako/tebako) supports Ruby 3.1 & 3.2
  - [ ] [ocran](https://github.com/largo/ocran) should work with 3.x rubies too
